// 섹션 6 — 회화 마스터 (CEFR B2)
// 원어민과 자연스럽게 대화하기: 구어체, 담화 표지, 완곡 표현, 리액션.

export const units = [
  {
    id: 's6u1',
    title: '스몰토크의 기술',
    subtitle: '자연스럽게 말 걸기',
    icon: 'chat',
    lessonCount: 5,
    pairs: [
      { ko: '요즘 어떻게 지내세요?', en: "How have you been doing lately?", alt: ["How have you been lately?"] },
      { ko: '오늘 날씨 정말 좋네요, 그렇죠?', en: "The weather is really nice today, right?", alt: ["The weather is so nice today, right?"] },
      { ko: '주말에 뭐 특별한 계획 있으세요?', en: "Do you have any special plans for the weekend?", alt: ["Any special plans for the weekend?"] },
      { ko: '지난 주말은 어떻게 보내셨어요?', en: "How did your weekend go?", alt: ["How was your weekend?"] },
      { ko: '시간 참 빠르네요. 벌써 칠월이에요.', en: "Time flies. It is already July.", alt: ["Time flies. It's already July."] },
      { ko: '우리 얘기 나눈 지 정말 오래됐네요.', en: "It has been so long since we talked.", alt: ["It's been so long since we talked.", "It has been a while since we talked."] },
      { ko: '요즘 일은 좀 어때요?', en: "How is work going these days?", alt: ["How's work going these days?"] },
      { ko: '비가 올 것 같아요. 우산 챙기세요.', en: "It looks like rain. Take an umbrella.", alt: ["It looks like rain, so take an umbrella."] },
      { ko: '솔직히 이런 날씨가 그리웠어요.', en: "Honestly, I missed weather like this.", alt: ["To be honest, I missed weather like this."] },
      { ko: '근처에 새로 생긴 카페 가 보셨어요?', en: "Have you tried the new cafe nearby?", alt: ["Have you been to the new cafe nearby?"] },
      { ko: '만나서 반가웠어요. 조만간 또 봐요.', en: "It was great catching up. See you soon.", alt: ["It was nice catching up. See you soon."] },
      { ko: '그나저나, 가족들은 잘 지내요?', en: "By the way, how is your family doing?", alt: ["By the way, how's your family doing?"] },
    ],
    words: [
      { ko: '날씨', en: 'weather' },
      { ko: '주말', en: 'weekend' },
      { ko: '요즘', en: 'lately' },
      { ko: '계획', en: 'plans' },
      { ko: '잡담', en: 'small talk' },
      { ko: '어색한', en: 'awkward' },
      { ko: '습한', en: 'humid' },
      { ko: '안부', en: 'regards' },
    ],
    distractorsEn: ['kitchen', 'purple', 'library', 'pencil', 'garlic', 'window', 'thunder', 'baggage'],
    distractorsKo: ['부엌', '보라색', '도서관', '연필', '마늘', '창문', '천둥', '수하물'],
  },
  {
    id: 's6u2',
    title: '구어체와 슬랭',
    subtitle: '일상 속 구어 표현',
    icon: 'bolt',
    lessonCount: 5,
    pairs: [
      { ko: '이번 주말에 같이 놀래?', en: "Do you want to hang out this weekend?", alt: ["Wanna hang out this weekend?"] },
      { ko: '말도 안 돼! 진짜야?', en: "No way! Are you serious?", alt: ["No way! Are you for real?"] },
      { ko: '나 지금 좀 피곤한 것 같아.', en: "I am kind of tired right now.", alt: ["I'm kind of tired right now.", "I am sort of tired right now."] },
      { ko: '그 영화 완전 대박이었어.', en: "That movie was totally awesome.", alt: ["That movie was so awesome."] },
      { ko: '진정해, 별일 아니야.', en: "Chill out, it is not a big deal.", alt: ["Chill out, it's not a big deal.", "Relax, it is not a big deal."] },
      { ko: '나 오늘 완전 빈털터리야.', en: "I am totally broke today.", alt: ["I'm totally broke today."] },
      { ko: '농담이지? 믿을 수가 없네.', en: "Are you kidding me? I cannot believe it.", alt: ["Are you kidding? I can't believe it."] },
      { ko: '오늘 밤은 그냥 집에서 쉴래.', en: "I just want to chill at home tonight.", alt: ["I just wanna chill at home tonight."] },
      { ko: '걔는 정말 느긋한 사람이야.', en: "He is such a laid back guy.", alt: ["He's such a laid back guy."] },
      { ko: '그건 좀 오버 아니야?', en: "Isn't that a bit over the top?", alt: ["Is that not a bit over the top?"] },
      { ko: '나중에 연락할게, 알았지?', en: "I will hit you up later, okay?", alt: ["I'll hit you up later, okay?"] },
      { ko: '어젯밤 파티는 완전 엉망이었어.', en: "The party last night was a total mess.", alt: ["Last night's party was a total mess."] },
    ],
    words: [
      { ko: '놀다', en: 'hang out' },
      { ko: '약간', en: 'kind of' },
      { ko: '대박인', en: 'awesome' },
      { ko: '빈털터리인', en: 'broke' },
      { ko: '느긋한', en: 'laid back' },
      { ko: '진정하다', en: 'chill' },
      { ko: '완전', en: 'totally' },
      { ko: '엉망', en: 'mess' },
    ],
    distractorsEn: ['salad', 'window', 'teacher', 'yellow', 'bridge', 'cloudy', 'spoon', 'ninety'],
    distractorsKo: ['샐러드', '창문', '선생님', '노란색', '다리', '흐린', '숟가락', '아흔'],
  },
  {
    id: 's6u3',
    title: '뉘앙스와 완곡',
    subtitle: '부드럽게 말하기',
    icon: 'face',
    lessonCount: 5,
    pairs: [
      { ko: '죄송하지만 이번에는 어려울 것 같아요.', en: "I am afraid I cannot make it this time.", alt: ["I'm afraid I can't make it this time."] },
      { ko: '괜찮으시다면 창문 좀 열어도 될까요?', en: "Would you mind if I opened the window?", alt: ["Do you mind if I open the window?"] },
      { ko: '제 생각에는 그게 최선은 아닌 것 같아요.', en: "I am not sure that is the best idea.", alt: ["I'm not sure that's the best idea.", "I don't think that is the best idea."] },
      { ko: '혹시 도와주실 수 있을까 해서요.', en: "I was wondering if you could help me.", alt: ["I was wondering if you could help me out."] },
      { ko: '그건 좀 곤란할 수도 있어요.', en: "That might be a little tricky.", alt: ["That could be a little tricky."] },
      { ko: '솔직히 말하면 저는 좀 실망했어요.', en: "To be honest, I was a little disappointed.", alt: ["Honestly, I was a little disappointed."] },
      { ko: '다시 한번 생각해 보시는 게 어때요?', en: "Why don't you think it over one more time?", alt: ["Maybe you should think it over again."] },
      { ko: '부담 갖지 마시고 편하게 말씀하세요.', en: "Please feel free to speak your mind.", alt: ["Feel free to speak your mind."] },
      { ko: '오늘은 좀 힘들 것 같아요. 다음에 어때요?', en: "Today does not really work for me. How about next time?", alt: ["Today doesn't really work for me. How about next time?"] },
      { ko: '말씀 중에 죄송한데 잠깐 끼어들어도 될까요?', en: "Sorry to interrupt, but may I jump in?", alt: ["Sorry to interrupt, but can I jump in?"] },
      { ko: '나쁘지 않은데 조금 아쉬운 부분이 있어요.', en: "It is not bad, but something feels missing.", alt: ["It's not bad, but something feels missing."] },
      { ko: '가능하시면 조금 일찍 와 주시겠어요?', en: "Could you possibly come a little earlier?", alt: ["Would you possibly come a little earlier?", "Could you please come a little earlier?"] },
    ],
    words: [
      { ko: '완곡한', en: 'indirect' },
      { ko: '거절하다', en: 'decline' },
      { ko: '부탁', en: 'favor' },
      { ko: '아마도', en: 'perhaps' },
      { ko: '실망한', en: 'disappointed' },
      { ko: '곤란한', en: 'tricky' },
      { ko: '끼어들다', en: 'interrupt' },
      { ko: '예의 바른', en: 'polite' },
    ],
    distractorsEn: ['banana', 'rocket', 'purple', 'kitchen', 'seventy', 'blanket', 'guitar', 'harbor'],
    distractorsKo: ['바나나', '로켓', '보라색', '부엌', '일흔', '담요', '기타', '항구'],
  },
  {
    id: 's6u4',
    title: '깊은 대화',
    subtitle: '마음을 나누는 말',
    icon: 'heart',
    lessonCount: 5,
    pairs: [
      { ko: '요즘 가장 큰 고민이 뭐예요?', en: "What is your biggest worry these days?", alt: ["What's your biggest worry these days?"] },
      { ko: '저에게 가족은 무엇보다 중요해요.', en: "My family matters more than anything to me.", alt: ["Family matters more than anything to me."] },
      { ko: '십 년 후에 어떤 모습이고 싶어요?', en: "Where do you see yourself in ten years?", alt: ["Where do you see yourself ten years from now?"] },
      { ko: '솔직히 저는 실패가 두려워요.', en: "To be honest, I am afraid of failure.", alt: ["Honestly, I'm afraid of failure.", "To be honest, I'm afraid of failure."] },
      { ko: '돈보다 시간이 더 소중하다고 생각해요.', en: "I think time is more precious than money.", alt: ["I believe time is more precious than money."] },
      { ko: '당신을 계속 나아가게 하는 힘은 뭔가요?', en: "What keeps you going when things get hard?", alt: ["What keeps you moving when things get hard?"] },
      { ko: '저는 작은 것에서 행복을 찾으려고 해요.', en: "I try to find happiness in small things.", alt: ["I try to find joy in small things."] },
      { ko: '그 결정을 후회한 적 있어요?', en: "Have you ever regretted that decision?", alt: ["Do you ever regret that decision?"] },
      { ko: '마음을 털어놓으니 한결 가벼워요.', en: "I feel much lighter after opening up.", alt: ["I feel so much lighter after opening up."] },
      { ko: '인생에서 성공이란 뭐라고 생각해요?', en: "What does success in life mean to you?", alt: ["What does success mean to you in life?"] },
      { ko: '실수도 결국 성장의 일부라고 믿어요.', en: "I believe mistakes are part of how we grow.", alt: ["I think mistakes are part of how we grow."] },
      { ko: '언제든 저한테 기대도 괜찮아요.', en: "You can always lean on me, okay?", alt: ["You can lean on me anytime, okay?"] },
    ],
    words: [
      { ko: '가치관', en: 'values' },
      { ko: '목표', en: 'goal' },
      { ko: '고민', en: 'worry' },
      { ko: '실패', en: 'failure' },
      { ko: '후회하다', en: 'regret' },
      { ko: '소중한', en: 'precious' },
      { ko: '성장', en: 'growth' },
      { ko: '진심', en: 'sincerity' },
    ],
    distractorsEn: ['bicycle', 'orange', 'stadium', 'pepper', 'eleven', 'jacket', 'planet', 'castle'],
    distractorsKo: ['자전거', '주황색', '경기장', '후추', '열하나', '재킷', '행성', '성벽'],
  },
  {
    id: 's6u5',
    title: '스토리텔링',
    subtitle: '이야기 들려주기',
    icon: 'book',
    lessonCount: 5,
    pairs: [
      { ko: '어제 무슨 일이 있었는지 믿기지 않을걸.', en: "You won't believe what happened to me yesterday.", alt: ["You will not believe what happened to me yesterday."] },
      { ko: '그래서 내가 뭐라고 했는지 알아?', en: "So do you know what I said?", alt: ["So guess what I said."] },
      { ko: '내가 막 나가려던 참이었는데 전화가 울렸어.', en: "I was just about to leave when the phone rang.", alt: ["I was about to leave when the phone rang."] },
      { ko: '갑자기 불이 다 꺼져 버린 거야.', en: "All of a sudden, the lights went out.", alt: ["Suddenly, all the lights went out."] },
      { ko: '알고 보니 그 사람이 내 옛 이웃이었어.', en: "It turns out he was my old neighbor.", alt: ["It turned out he was my old neighbor."] },
      { ko: '요약하자면, 우리는 마지막 기차를 놓쳤어.', en: "Long story short, we missed the last train.", alt: ["To make a long story short, we missed the last train."] },
      { ko: '그 순간 내 심장이 멎는 줄 알았어.', en: "I thought my heart stopped at that moment.", alt: ["At that moment, I thought my heart stopped."] },
      { ko: '처음에는 그게 농담인 줄 알았지.', en: "At first, I thought it was a joke.", alt: ["At first I thought it was a joke."] },
      { ko: '그러다가 상황이 정말 이상해지기 시작했어.', en: "Then things started to get really weird.", alt: ["And then things started to get really weird."] },
      { ko: '결국 우리는 그 일로 한참 웃었어.', en: "In the end, we laughed about it for ages.", alt: ["In the end, we laughed about it a lot."] },
      { ko: '더 재밌는 건, 그가 사과도 안 했다는 거야.', en: "The funny thing is, he never even apologized.", alt: ["The funniest part is, he never even apologized."] },
      { ko: '있잖아, 나 오늘 정말 이상한 걸 봤어.', en: "You know, I saw something really strange today.", alt: ["You know what, I saw something really strange today."] },
    ],
    words: [
      { ko: '일화', en: 'anecdote' },
      { ko: '갑자기', en: 'suddenly' },
      { ko: '결국', en: 'eventually' },
      { ko: '줄거리', en: 'plot' },
      { ko: '이상한', en: 'weird' },
      { ko: '웃긴', en: 'hilarious' },
      { ko: '순간', en: 'moment' },
      { ko: '뒷이야기', en: 'backstory' },
    ],
    distractorsEn: ['garden', 'silver', 'cheese', 'forty', 'pillow', 'doctor', 'summer', 'ticket'],
    distractorsKo: ['정원', '은색', '치즈', '마흔', '베개', '의사', '여름', '입장권'],
  },
  {
    id: 's6u6',
    title: '원어민처럼',
    subtitle: '리액션과 맞장구',
    icon: 'crown',
    lessonCount: 5,
    pairs: [
      { ko: '와, 그거 정말 대단하다!', en: "Wow, that is really impressive!", alt: ["Wow, that's really impressive!"] },
      { ko: '진짜? 전혀 몰랐어.', en: "Really? I had no idea.", alt: ["Seriously? I had no idea."] },
      { ko: '무슨 말인지 알겠어.', en: "I see what you mean.", alt: ["I know what you mean."] },
      { ko: '그러게 말이야, 완전 동감이야.', en: "Tell me about it, I totally agree.", alt: ["Tell me about it, I completely agree."] },
      { ko: '설마, 그건 말도 안 돼.', en: "Come on, there is no way.", alt: ["Come on, there's no way."] },
      { ko: '어머, 정말 안타깝다.', en: "Oh no, that is such a shame.", alt: ["Oh no, that's such a shame."] },
      { ko: '잠깐만, 그게 무슨 뜻이야?', en: "Wait a second, what do you mean?", alt: ["Wait a minute, what do you mean?"] },
      { ko: '아 맞다, 깜빡할 뻔했네.', en: "Oh right, I almost forgot about that.", alt: ["Oh right, I almost forgot."] },
      { ko: '음, 어떻게 말해야 할지 모르겠네.', en: "Well, I am not sure how to say this.", alt: ["Well, I'm not sure how to put this."] },
      { ko: '그거 잘됐다! 축하해!', en: "That is great news! Congratulations!", alt: ["That's great news! Congratulations!"] },
      { ko: '맞아 맞아, 바로 그거야.', en: "Exactly, that is what I am talking about.", alt: ["Exactly, that's what I'm talking about."] },
      { ko: '어쨌든, 잘 해결돼서 다행이야.', en: "Anyway, I am glad it all worked out.", alt: ["Anyway, I'm glad it all worked out."] },
    ],
    words: [
      { ko: '정확히', en: 'exactly' },
      { ko: '진심으로', en: 'seriously' },
      { ko: '인상적인', en: 'impressive' },
      { ko: '유감', en: 'shame' },
      { ko: '동의하다', en: 'agree' },
      { ko: '추임새', en: 'filler' },
      { ko: '반응', en: 'reaction' },
      { ko: '어쨌든', en: 'anyway' },
    ],
    distractorsEn: ['tomato', 'winter', 'eighty', 'lamp', 'violet', 'muscle', 'engine', 'sailor'],
    distractorsKo: ['토마토', '겨울', '여든', '램프', '보라', '근육', '엔진', '선원'],
  },
];
