// 섹션 5 — 실전 영어 (CEFR B1+)
// 문법: 가정법 1·2식, 수동태 기초, 관용어구, used to, 구동사

export const units = [
  {
    id: 's5u1',
    title: '가정과 상상',
    subtitle: '만약을 말하는 법',
    icon: 'bolt',
    lessonCount: 5,
    pairs: [
      { ko: '내가 너라면 그 일자리를 받아들일 거야.', en: "If I were you, I would take the job.", alt: ["If I were you, I'd take the job."] },
      { ko: '비가 오면 우리는 집에 있을 거예요.', en: "If it rains, we will stay home.", alt: ["If it rains, we'll stay home.", "If it rains, we will stay at home."] },
      { ko: '복권에 당첨되면 뭐 할 거야?', en: "What will you do if you win the lottery?", alt: [] },
      { ko: '돈이 더 있다면 세계를 여행할 텐데.', en: "If I had more money, I would travel the world.", alt: ["If I had more money, I'd travel the world."] },
      { ko: '날 수 있다면 정말 멋질 거야.', en: "It would be amazing if I could fly.", alt: [] },
      { ko: '서두르지 않으면 버스를 놓칠 거예요.', en: "If you do not hurry, you will miss the bus.", alt: ["If you don't hurry, you'll miss the bus.", "If you don't hurry, you will miss the bus."] },
      { ko: '내가 부자라면 큰 집을 살 텐데.', en: "If I were rich, I would buy a big house.", alt: ["If I were rich, I'd buy a big house."] },
      { ko: '질문이 있으면 언제든지 전화하세요.', en: "If you have any questions, please call me anytime.", alt: ["Please call me anytime if you have any questions."] },
      { ko: '시간이 있다면 운동을 더 할 텐데.', en: "If I had time, I would exercise more.", alt: ["If I had time, I'd exercise more."] },
      { ko: '그가 늦으면 우리는 그 없이 시작할 거예요.', en: "If he is late, we will start without him.", alt: ["If he's late, we'll start without him."] },
      { ko: '만약 하루가 더 길다면 뭐 하고 싶어?', en: "What would you do if days were longer?", alt: [] },
      { ko: '내일 날씨가 좋으면 소풍 가자.', en: "Let's go on a picnic if the weather is nice tomorrow.", alt: ["If the weather is nice tomorrow, let's go on a picnic."] },
    ],
    words: [
      { ko: '만약', en: 'if' },
      { ko: '복권', en: 'lottery' },
      { ko: '상상하다', en: 'imagine' },
      { ko: '소원', en: 'wish' },
      { ko: '가능성', en: 'chance' },
      { ko: '미래', en: 'future' },
      { ko: '상황', en: 'situation' },
      { ko: '아마', en: 'maybe' },
    ],
    distractorsEn: ['yesterday', 'kitchen', 'purple', 'sings', 'window', 'cloud', 'teacher', 'bicycle'],
    distractorsKo: ['어제', '부엌', '보라색', '노래해요', '창문', '구름', '선생님', '자전거'],
  },
  {
    id: 's5u2',
    title: '관용 표현',
    subtitle: '자주 쓰는 관용어',
    icon: 'star',
    lessonCount: 5,
    pairs: [
      { ko: '그 시험은 정말 식은 죽 먹기였어.', en: "The test was a piece of cake.", alt: ["That test was a piece of cake."] },
      { ko: '오늘 밤 공연 잘해, 행운을 빌어!', en: "Break a leg at the show tonight!", alt: ["Good luck at the show tonight!"] },
      { ko: '나 오늘 몸이 좀 안 좋아.', en: "I am feeling a little under the weather today.", alt: ["I'm feeling a little under the weather today.", "I feel a bit under the weather today."] },
      { ko: '이 차는 엄청나게 비쌌어.', en: "This car cost an arm and a leg.", alt: [] },
      { ko: '우리는 아주 가끔 외식을 해요.', en: "We eat out once in a blue moon.", alt: [] },
      { ko: '피곤해서 이제 자러 갈래.', en: "I am tired, so I will hit the sack.", alt: ["I'm tired, so I'll hit the sack."] },
      { ko: '누가 깜짝 파티에 대해 비밀을 말해버렸어?', en: "Who spilled the beans about the surprise party?", alt: [] },
      { ko: '우리 생각이 같은지 확인하자.', en: "Let's make sure we are on the same page.", alt: ["Let's make sure we're on the same page."] },
      { ko: '오늘은 여기까지 하고 집에 갑시다.', en: "Let's call it a day and go home.", alt: ["Let's call it a day."] },
      { ko: '밖에 비가 억수같이 쏟아지고 있어.', en: "It is raining cats and dogs outside.", alt: ["It's raining cats and dogs outside."] },
      { ko: '내 가방 좀 잠깐 봐줄 수 있어?', en: "Can you keep an eye on my bag for a minute?", alt: ["Could you keep an eye on my bag for a minute?"] },
      { ko: '진정해, 너무 긴장하지 마.', en: "Take it easy, do not be so nervous.", alt: ["Take it easy, don't be so nervous."] },
    ],
    words: [
      { ko: '관용구', en: 'idiom' },
      { ko: '조각', en: 'piece' },
      { ko: '행운', en: 'luck' },
      { ko: '날씨', en: 'weather' },
      { ko: '비밀', en: 'secret' },
      { ko: '표현', en: 'expression' },
      { ko: '의미', en: 'meaning' },
      { ko: '농담', en: 'joke' },
    ],
    distractorsEn: ['mountain', 'yellow', 'swims', 'library', 'orange', 'pencil', 'river', 'cousin'],
    distractorsKo: ['산', '노란색', '수영해요', '도서관', '오렌지', '연필', '강', '사촌'],
  },
  {
    id: 's5u3',
    title: '일과 비즈니스',
    subtitle: '회사에서 쓰는 영어',
    icon: 'chart',
    lessonCount: 5,
    pairs: [
      { ko: '회의가 오후 세 시로 옮겨졌어요.', en: "The meeting was moved to three in the afternoon.", alt: ["The meeting has been moved to three in the afternoon."] },
      { ko: '제가 오늘 아침에 그 이메일을 보냈어요.', en: "I sent the email this morning.", alt: ["I sent that email this morning."] },
      { ko: '보고서는 금요일까지 제출되어야 해요.', en: "The report must be submitted by Friday.", alt: ["The report has to be submitted by Friday."] },
      { ko: '마감일을 다음 주로 미룰 수 있을까요?', en: "Can we push the deadline to next week?", alt: ["Could we push the deadline to next week?", "Can we move the deadline to next week?"] },
      { ko: '그 프로젝트는 우리 팀이 맡고 있어요.', en: "The project is handled by our team.", alt: ["Our team handles the project.", "Our team is handling the project."] },
      { ko: '발표 준비는 다 됐나요?', en: "Are you ready for the presentation?", alt: ["Is the presentation ready?"] },
      { ko: '저는 동료들과 잘 지내요.', en: "I get along with my coworkers.", alt: ["I get along well with my coworkers.", "I get along with my colleagues."] },
      { ko: '그녀는 회의에서 새로운 아이디어를 제안했어요.', en: "She came up with a new idea at the meeting.", alt: ["She suggested a new idea at the meeting."] },
      { ko: '이 서류 좀 검토해 주시겠어요?', en: "Could you look over this document for me?", alt: ["Can you look over this document for me?", "Could you review this document for me?"] },
      { ko: '급한 일이 생겨서 회의를 취소했어요.', en: "We called off the meeting because something urgent came up.", alt: ["The meeting was called off because something urgent came up."] },
      { ko: '그 자리에 새 매니저가 채용되었어요.', en: "A new manager was hired for the position.", alt: ["A new manager has been hired for the position."] },
      { ko: '오늘 회사에서 정말 바쁜 하루였어요.', en: "It was a really busy day at work today.", alt: ["Today was a really busy day at work."] },
    ],
    words: [
      { ko: '회의', en: 'meeting' },
      { ko: '마감일', en: 'deadline' },
      { ko: '보고서', en: 'report' },
      { ko: '동료', en: 'coworker' },
      { ko: '발표', en: 'presentation' },
      { ko: '서류', en: 'document' },
      { ko: '매니저', en: 'manager' },
      { ko: '사무실', en: 'office' },
    ],
    distractorsEn: ['banana', 'winter', 'dances', 'ocean', 'guitar', 'rabbit', 'cloudy', 'spoon'],
    distractorsKo: ['바나나', '겨울', '춤춰요', '바다', '기타', '토끼', '흐린', '숟가락'],
  },
  {
    id: 's5u4',
    title: '여행 트러블',
    subtitle: '여행 문제 해결하기',
    icon: 'plane',
    lessonCount: 5,
    pairs: [
      { ko: '제 수하물이 아직 도착하지 않았어요.', en: "My luggage has not arrived yet.", alt: ["My luggage hasn't arrived yet.", "My baggage has not arrived yet."] },
      { ko: '비행기가 두 시간 연착되었어요.', en: "The flight was delayed for two hours.", alt: ["The flight has been delayed for two hours.", "My flight was delayed for two hours."] },
      { ko: '이 표를 환불받을 수 있을까요?', en: "Can I get a refund for this ticket?", alt: ["Could I get a refund for this ticket?"] },
      { ko: '예약을 다음 주 화요일로 변경하고 싶어요.', en: "I would like to change my reservation to next Tuesday.", alt: ["I'd like to change my reservation to next Tuesday.", "I want to change my reservation to next Tuesday."] },
      { ko: '공항에서 여권을 잃어버린 것 같아요.', en: "I think I lost my passport at the airport.", alt: ["I think I lost my passport in the airport."] },
      { ko: '호텔 방에서 와이파이가 안 돼요.', en: "The wifi does not work in my hotel room.", alt: ["The wifi doesn't work in my hotel room.", "The wifi is not working in my hotel room."] },
      { ko: '연결 항공편을 놓쳤는데 어떻게 해야 하나요?', en: "I missed my connecting flight, so what should I do?", alt: ["I missed my connecting flight, what should I do?"] },
      { ko: '분실물 센터가 어디에 있는지 아세요?', en: "Do you know where the lost and found is?", alt: [] },
      { ko: '방을 바꿔 주실 수 있나요? 너무 시끄러워요.', en: "Could you change my room? It is too noisy.", alt: ["Could you change my room? It's too noisy.", "Can you change my room? It is too noisy."] },
      { ko: '다음 기차는 언제 출발하나요?', en: "When does the next train leave?", alt: ["What time does the next train leave?"] },
      { ko: '문제가 해결될 때까지 여기서 기다릴게요.', en: "I will wait here until the problem is solved.", alt: ["I'll wait here until the problem is solved."] },
      { ko: '이 문제를 도와주셔서 정말 감사합니다.', en: "Thank you so much for helping me with this problem.", alt: ["Thanks so much for helping me with this problem.", "Thank you so much for your help with this problem."] },
    ],
    words: [
      { ko: '수하물', en: 'luggage' },
      { ko: '항공편', en: 'flight' },
      { ko: '환불', en: 'refund' },
      { ko: '예약', en: 'reservation' },
      { ko: '여권', en: 'passport' },
      { ko: '공항', en: 'airport' },
      { ko: '연착', en: 'delay' },
      { ko: '승객', en: 'passenger' },
    ],
    distractorsEn: ['chicken', 'forest', 'piano', 'happy', 'garden', 'silver', 'monkey', 'bakery'],
    distractorsKo: ['치킨', '숲', '피아노', '행복한', '정원', '은색', '원숭이', '빵집'],
  },
  {
    id: 's5u5',
    title: '문화와 취향',
    subtitle: '감상과 추천 표현',
    icon: 'sun',
    lessonCount: 5,
    pairs: [
      { ko: '나는 예전에 록 음악을 많이 들었어.', en: "I used to listen to rock music a lot.", alt: ["I used to listen to a lot of rock music."] },
      { ko: '그 영화는 소설을 원작으로 만들어졌어.', en: "The movie was based on a novel.", alt: ["The film was based on a novel."] },
      { ko: '어젯밤에 본 드라마 정말 재미있었어.', en: "The show I watched last night was really fun.", alt: ["The drama I watched last night was really fun."] },
      { ko: '이 책을 읽어 보는 걸 강력히 추천해.', en: "I highly recommend reading this book.", alt: ["I strongly recommend reading this book.", "I highly recommend that you read this book."] },
      { ko: '결말이 너무 슬퍼서 나는 울고 말았어.', en: "The ending was so sad that I cried.", alt: ["The ending was so sad I cried."] },
      { ko: '너는 어떤 종류의 음악을 즐겨 들어?', en: "What kind of music do you like to listen to?", alt: ["What kind of music do you enjoy listening to?"] },
      { ko: '그 밴드는 우리나라에서 정말 인기가 많아.', en: "That band is really popular in my country.", alt: ["The band is really popular in my country."] },
      { ko: '나는 공포 영화보다 코미디가 더 좋아.', en: "I like comedies better than horror movies.", alt: ["I like comedies more than horror movies.", "I prefer comedies to horror movies."] },
      { ko: '주말마다 나는 미술관에 가곤 했어.', en: "I used to go to the art museum every weekend.", alt: ["Every weekend I used to go to the art museum."] },
      { ko: '그 노래를 들으면 학창 시절이 떠올라.', en: "That song reminds me of my school days.", alt: ["The song reminds me of my school days."] },
      { ko: '이 소설은 열 개 언어로 번역되었어.', en: "This novel was translated into ten languages.", alt: ["This novel has been translated into ten languages."] },
      { ko: '취향은 사람마다 다른 것 같아.', en: "I think everyone has different tastes.", alt: ["Everyone has different tastes, I think."] },
    ],
    words: [
      { ko: '영화', en: 'movie' },
      { ko: '소설', en: 'novel' },
      { ko: '결말', en: 'ending' },
      { ko: '취향', en: 'taste' },
      { ko: '추천하다', en: 'recommend' },
      { ko: '인기 있는', en: 'popular' },
      { ko: '박물관', en: 'museum' },
      { ko: '가수', en: 'singer' },
    ],
    distractorsEn: ['tomato', 'bridge', 'soccer', 'candle', 'pepper', 'turtle', 'jacket', 'stone'],
    distractorsKo: ['토마토', '다리', '축구', '양초', '후추', '거북이', '재킷', '돌'],
  },
  {
    id: 's5u6',
    title: '토론 입문',
    subtitle: '의견 주고받기',
    icon: 'chat',
    lessonCount: 5,
    pairs: [
      { ko: '제 생각에는 그 계획에 장점이 더 많아요.', en: "In my opinion, the plan has more advantages.", alt: ["In my opinion, that plan has more advantages."] },
      { ko: '왜 그렇게 생각하는지 설명해 주시겠어요?', en: "Could you explain why you think so?", alt: ["Can you explain why you think so?"] },
      { ko: '일리가 있지만 저는 동의하지 않아요.', en: "You have a point, but I disagree.", alt: ["That's a good point, but I disagree.", "You have a point, but I do not agree."] },
      { ko: '예를 들어 많은 학생들이 온라인 수업을 선호해요.', en: "For example, many students prefer online classes.", alt: ["For instance, many students prefer online classes."] },
      { ko: '그 주장을 뒷받침할 근거가 있나요?', en: "Do you have any evidence to support that claim?", alt: ["Is there any evidence to support that claim?"] },
      { ko: '어느 정도는 맞지만 문제가 하나 있어요.', en: "That is true to some extent, but there is one problem.", alt: ["That's true to some extent, but there is one problem."] },
      { ko: '반면에 어떤 사람들은 그 반대라고 믿어요.', en: "On the other hand, some people believe the opposite.", alt: [] },
      { ko: '결론적으로 저는 그 제안을 지지해요.', en: "In conclusion, I support the proposal.", alt: ["In conclusion, I agree with the proposal."] },
      { ko: '당신의 의견을 존중하지만 사실은 다르게 말해요.', en: "I respect your opinion, but the facts say otherwise.", alt: [] },
      { ko: '핵심은 우리에게 시간이 많지 않다는 거예요.', en: "The point is that we do not have much time.", alt: ["The point is that we don't have much time."] },
      { ko: '두 의견 모두 장단점이 있다고 생각해요.', en: "I think both opinions have strengths and weaknesses.", alt: ["I think both views have strengths and weaknesses."] },
      { ko: '먼저 상대방의 이야기를 끝까지 들어봐야 해요.', en: "You should hear the other side out first.", alt: ["You should hear the other person out first."] },
    ],
    words: [
      { ko: '의견', en: 'opinion' },
      { ko: '근거', en: 'evidence' },
      { ko: '주장', en: 'claim' },
      { ko: '동의하다', en: 'agree' },
      { ko: '반대하다', en: 'disagree' },
      { ko: '토론', en: 'debate' },
      { ko: '결론', en: 'conclusion' },
      { ko: '제안', en: 'proposal' },
    ],
    distractorsEn: ['butter', 'grape', 'snowy', 'ladder', 'violin', 'pocket', 'shrimp', 'meadow'],
    distractorsKo: ['버터', '포도', '눈 오는', '사다리', '바이올린', '주머니', '새우', '초원'],
  },
];
