// 섹션 3 — CEFR A2 「표현의 확장」
// 문법: 과거시제(규칙/불규칙), be going to / will, 현재진행, because/so, 비교급 맛보기

export const units = [
  {
    id: 's3u1',
    title: '지난 이야기',
    subtitle: '어제 있었던 일',
    icon: 'book',
    lessonCount: 5,
    pairs: [
      { ko: '나는 어제 영화를 봤어요.', en: 'I watched a movie yesterday.', alt: ['Yesterday I watched a movie.'] },
      { ko: '우리는 지난주에 부산에 갔어요.', en: 'We went to Busan last week.', alt: ['Last week we went to Busan.'] },
      { ko: '그는 어젯밤에 늦게 잤어요.', en: 'He went to bed late last night.', alt: ['He went to sleep late last night.'] },
      { ko: '나는 아침으로 빵을 먹었어요.', en: 'I ate bread for breakfast.', alt: ['I had bread for breakfast.'] },
      { ko: '그녀는 어제 친구를 만났어요.', en: 'She met her friend yesterday.', alt: ['She met a friend yesterday.'] },
      { ko: '나는 지난 주말에 집을 청소했어요.', en: 'I cleaned my house last weekend.', alt: ['I cleaned the house last weekend.'] },
      { ko: '우리는 어제 축구를 했어요.', en: 'We played soccer yesterday.', alt: ['Yesterday we played soccer.'] },
      { ko: '나는 어제 일찍 일어나지 않았어요.', en: 'I did not get up early yesterday.', alt: ["I didn't get up early yesterday."] },
      { ko: '어제 뭐 했어요?', en: 'What did you do yesterday?', alt: [] },
      { ko: '그들은 지난달에 새 차를 샀어요.', en: 'They bought a new car last month.', alt: ['Last month they bought a new car.'] },
      { ko: '나는 어제 하루 종일 공부했어요.', en: 'I studied all day yesterday.', alt: ['Yesterday I studied all day.'] },
      { ko: '그는 파티에서 정말 즐거웠어요.', en: 'He had a great time at the party.', alt: ['He had a really good time at the party.'] },
    ],
    words: [
      { ko: '어제', en: 'yesterday' },
      { ko: '지난주', en: 'last week' },
      { ko: '보았다', en: 'watched' },
      { ko: '갔다', en: 'went' },
      { ko: '먹었다', en: 'ate' },
      { ko: '샀다', en: 'bought' },
      { ko: '만났다', en: 'met' },
      { ko: '청소했다', en: 'cleaned' },
    ],
    distractorsEn: ['tomorrow', 'drink', 'swim', 'window', 'kitchen', 'purple', 'seven', 'runs'],
    distractorsKo: ['내일', '마셨다', '수영', '창문', '부엌', '보라색', '일곱', '달린다'],
  },
  {
    id: 's3u2',
    title: '계획과 미래',
    subtitle: '주말 계획 세우기',
    icon: 'bolt',
    lessonCount: 5,
    pairs: [
      { ko: '나는 이번 주말에 등산을 갈 거예요.', en: 'I am going to go hiking this weekend.', alt: ["I'm going to go hiking this weekend."] },
      { ko: '우리는 내일 소풍을 갈 거예요.', en: 'We are going to have a picnic tomorrow.', alt: ["We're going to have a picnic tomorrow."] },
      { ko: '그녀는 다음 달에 이사할 거예요.', en: 'She is going to move next month.', alt: ["She's going to move next month."] },
      { ko: '방학 동안 뭐 할 거예요?', en: 'What are you going to do during the vacation?', alt: ['What will you do during the vacation?'] },
      { ko: '오늘 밤에는 제가 저녁을 요리할게요.', en: 'I will cook dinner tonight.', alt: ["I'll cook dinner tonight."] },
      { ko: '그는 오늘 밤에 일찍 잘 거예요.', en: 'He will go to bed early tonight.', alt: ["He'll go to bed early tonight."] },
      { ko: '우리는 다음 주에 할머니를 방문할 거예요.', en: 'We will visit our grandmother next week.', alt: ["We'll visit our grandmother next week."] },
      { ko: '곧 비가 올 거예요.', en: 'It is going to rain soon.', alt: ["It's going to rain soon."] },
      { ko: '나는 내년에 영어를 열심히 공부할 거예요.', en: 'I am going to study English hard next year.', alt: ["I'm going to study English hard next year."] },
      { ko: '몇 시에 출발할 거예요?', en: 'What time are you going to leave?', alt: ['What time will you leave?'] },
      { ko: '그들은 토요일에 파티를 열 거예요.', en: 'They are going to have a party on Saturday.', alt: ["They're going to have a party on Saturday."] },
      { ko: '걱정하지 마세요, 제가 도와줄게요.', en: "Don't worry, I will help you.", alt: ["Don't worry, I'll help you."] },
    ],
    words: [
      { ko: '내일', en: 'tomorrow' },
      { ko: '주말', en: 'weekend' },
      { ko: '방학', en: 'vacation' },
      { ko: '계획', en: 'plan' },
      { ko: '소풍', en: 'picnic' },
      { ko: '이사하다', en: 'move' },
      { ko: '방문하다', en: 'visit' },
      { ko: '출발하다', en: 'leave' },
    ],
    distractorsEn: ['yesterday', 'kitchen', 'apple', 'window', 'teacher', 'winter', 'shoes', 'small'],
    distractorsKo: ['어제', '부엌', '사과', '선생님', '겨울', '신발', '작다', '책상'],
  },
  {
    id: 's3u3',
    title: '건강',
    subtitle: '아플 때 말하기',
    icon: 'heart',
    lessonCount: 5,
    pairs: [
      { ko: '머리가 아파요.', en: 'I have a headache.', alt: ["I've got a headache."] },
      { ko: '목이 아파요.', en: 'I have a sore throat.', alt: ["I've got a sore throat."] },
      { ko: '열이 나고 기침을 해요.', en: 'I have a fever and a cough.', alt: ['I have a fever and I am coughing.'] },
      { ko: '어제 병원에 갔어요.', en: 'I went to the hospital yesterday.', alt: ['Yesterday I went to the hospital.'] },
      { ko: '의사 선생님이 푹 쉬라고 했어요.', en: 'The doctor told me to get some rest.', alt: ['The doctor told me to rest a lot.'] },
      { ko: '약국이 어디에 있나요?', en: 'Where is the pharmacy?', alt: ['Where is the drugstore?'] },
      { ko: '하루에 세 번 이 약을 드세요.', en: 'Take this medicine three times a day.', alt: ['Please take this medicine three times a day.'] },
      { ko: '몸이 좀 나아졌어요.', en: 'I feel a little better now.', alt: ['I am feeling a little better now.', "I'm feeling a little better now."] },
      { ko: '따뜻한 물을 많이 마시는 게 좋아요.', en: 'You should drink a lot of warm water.', alt: ['You should drink lots of warm water.'] },
      { ko: '감기에 걸린 것 같아요.', en: 'I think I have a cold.', alt: ['I think I caught a cold.'] },
      { ko: '다리를 다쳐서 걸을 수 없어요.', en: "I hurt my leg, so I can't walk.", alt: ['I hurt my leg, so I cannot walk.'] },
      { ko: '건강을 위해 매일 운동하세요.', en: 'Exercise every day for your health.', alt: ['Please exercise every day for your health.'] },
    ],
    words: [
      { ko: '머리', en: 'head' },
      { ko: '열', en: 'fever' },
      { ko: '기침', en: 'cough' },
      { ko: '병원', en: 'hospital' },
      { ko: '약', en: 'medicine' },
      { ko: '의사', en: 'doctor' },
      { ko: '감기', en: 'cold' },
      { ko: '아픈', en: 'sick' },
    ],
    distractorsEn: ['happy', 'window', 'train', 'blue', 'chair', 'banana', 'rainy', 'shoes'],
    distractorsKo: ['행복하다', '기차', '파란색', '의자', '바나나', '신발', '창문', '구름'],
  },
  {
    id: 's3u4',
    title: '집과 동네',
    subtitle: '집안일과 동네 시설',
    icon: 'chat',
    lessonCount: 5,
    pairs: [
      { ko: '우리 집에는 방이 세 개 있어요.', en: 'There are three rooms in my house.', alt: ['My house has three rooms.'] },
      { ko: '부엌이 거실보다 더 작아요.', en: 'The kitchen is smaller than the living room.', alt: ['Our kitchen is smaller than the living room.'] },
      { ko: '나는 매주 토요일에 방을 청소해요.', en: 'I clean my room every Saturday.', alt: ['Every Saturday I clean my room.'] },
      { ko: '어젯밤에 설거지를 했어요.', en: 'I did the dishes last night.', alt: ['I washed the dishes last night.'] },
      { ko: '우리 동네에는 큰 공원이 있어요.', en: 'There is a big park in my neighborhood.', alt: ["There's a big park in my neighborhood."] },
      { ko: '은행은 서점 옆에 있어요.', en: 'The bank is next to the bookstore.', alt: ['The bank is right next to the bookstore.'] },
      { ko: '집이 역에서 가까워서 편해요.', en: "My house is near the station, so it's convenient.", alt: ['My house is near the station, so it is convenient.'] },
      { ko: '창문 좀 열어 줄래요?', en: 'Can you open the window, please?', alt: ['Could you open the window, please?'] },
      { ko: '그는 지금 마당에서 빨래를 널고 있어요.', en: 'He is hanging the laundry in the yard now.', alt: ["He's hanging the laundry in the yard now."] },
      { ko: '슈퍼마켓은 몇 시에 문을 닫아요?', en: 'What time does the supermarket close?', alt: ['When does the supermarket close?'] },
      { ko: '내 방은 이 층에 있어요.', en: 'My room is on the second floor.', alt: ['My bedroom is on the second floor.'] },
      { ko: '쓰레기 좀 버려 줄래요?', en: 'Can you take out the trash?', alt: ['Could you take out the trash?', 'Can you take the trash out?'] },
    ],
    words: [
      { ko: '부엌', en: 'kitchen' },
      { ko: '거실', en: 'living room' },
      { ko: '창문', en: 'window' },
      { ko: '마당', en: 'yard' },
      { ko: '동네', en: 'neighborhood' },
      { ko: '은행', en: 'bank' },
      { ko: '서점', en: 'bookstore' },
      { ko: '빨래', en: 'laundry' },
    ],
    distractorsEn: ['school', 'apple', 'yellow', 'doctor', 'rain', 'plane', 'happy', 'winter'],
    distractorsKo: ['학교', '사과', '노란색', '의사', '비행기', '겨울', '행복', '바다'],
  },
  {
    id: 's3u5',
    title: '감정 표현',
    subtitle: '기분 말하고 공감하기',
    icon: 'face',
    lessonCount: 5,
    pairs: [
      { ko: '오늘 정말 기분이 좋아요.', en: 'I feel really good today.', alt: ['I am feeling really good today.', "I'm feeling really good today."] },
      { ko: '그 소식을 들어서 정말 기뻐요.', en: 'I am so happy to hear that news.', alt: ["I'm so happy to hear that news."] },
      { ko: '시험 때문에 너무 긴장돼요.', en: 'I am so nervous because of the test.', alt: ["I'm so nervous because of the test."] },
      { ko: '어제 속상해서 많이 울었어요.', en: 'I was upset yesterday, so I cried a lot.', alt: ['I was sad yesterday, so I cried a lot.'] },
      { ko: '왜 그렇게 화가 났어요?', en: 'Why are you so angry?', alt: ['Why are you so mad?'] },
      { ko: '괜찮아요? 슬퍼 보여요.', en: 'Are you okay? You look sad.', alt: ['Are you all right? You look sad.'] },
      { ko: '그 말을 들으니 유감이에요.', en: 'I am sorry to hear that.', alt: ["I'm sorry to hear that."] },
      { ko: '걱정하지 마세요. 다 잘될 거예요.', en: "Don't worry. Everything will be fine.", alt: ['Do not worry. Everything will be fine.', "Don't worry. Everything is going to be fine."] },
      { ko: '무서운 영화를 봐서 잠을 못 잤어요.', en: "I watched a scary movie, so I couldn't sleep.", alt: ['I watched a scary movie, so I could not sleep.'] },
      { ko: '그는 선물을 받고 신났어요.', en: 'He was excited about the gift.', alt: ['He got excited about the gift.'] },
      { ko: '기운 내요! 제가 옆에 있잖아요.', en: 'Cheer up! I am here for you.', alt: ["Cheer up! I'm here for you."] },
      { ko: '피곤하면 좀 쉬어요.', en: 'If you are tired, get some rest.', alt: ["If you're tired, get some rest."] },
    ],
    words: [
      { ko: '행복한', en: 'happy' },
      { ko: '슬픈', en: 'sad' },
      { ko: '화난', en: 'angry' },
      { ko: '긴장한', en: 'nervous' },
      { ko: '신난', en: 'excited' },
      { ko: '피곤한', en: 'tired' },
      { ko: '무서운', en: 'scary' },
      { ko: '속상한', en: 'upset' },
    ],
    distractorsEn: ['kitchen', 'purple', 'bicycle', 'lunch', 'winter', 'table', 'seven', 'cloud'],
    distractorsKo: ['부엌', '보라색', '자전거', '점심', '겨울', '탁자', '일곱', '구름'],
  },
  {
    id: 's3u6',
    title: '학교와 공부',
    subtitle: '수업과 시험 이야기',
    icon: 'trophy',
    lessonCount: 5,
    pairs: [
      { ko: '나는 매일 저녁에 영어를 공부해요.', en: 'I study English every evening.', alt: ['Every evening I study English.'] },
      { ko: '수학 수업은 아홉 시에 시작해요.', en: 'Math class starts at nine.', alt: ['The math class starts at nine.'] },
      { ko: '어제 시험을 봐서 피곤해요.', en: 'I took a test yesterday, so I am tired.', alt: ["I took a test yesterday, so I'm tired."] },
      { ko: '그녀는 지금 도서관에서 공부하고 있어요.', en: 'She is studying at the library now.', alt: ["She's studying at the library now."] },
      { ko: '시험이 어려웠지만 통과했어요.', en: 'The test was hard, but I passed.', alt: ['The test was difficult, but I passed.'] },
      { ko: '숙제를 아직 다 못 끝냈어요.', en: 'I have not finished my homework yet.', alt: ["I haven't finished my homework yet."] },
      { ko: '내일 단어 시험이 있어서 공부해야 해요.', en: 'I have a word test tomorrow, so I have to study.', alt: ['I have a vocabulary test tomorrow, so I have to study.'] },
      { ko: '영어가 수학보다 더 재미있어요.', en: 'English is more fun than math.', alt: ['English is more interesting than math.'] },
      { ko: '질문이 있으면 손을 드세요.', en: 'Raise your hand if you have a question.', alt: ['If you have a question, raise your hand.'] },
      { ko: '그는 열심히 공부했기 때문에 시험을 잘 봤어요.', en: 'He did well on the test because he studied hard.', alt: ['Because he studied hard, he did well on the test.'] },
      { ko: '우리는 다음 주에 발표를 할 거예요.', en: 'We are going to give a presentation next week.', alt: ["We're going to give a presentation next week."] },
      { ko: '수업 시간에 필기를 하는 게 좋아요.', en: 'You should take notes in class.', alt: ['You should take notes during class.'] },
    ],
    words: [
      { ko: '시험', en: 'test' },
      { ko: '숙제', en: 'homework' },
      { ko: '수업', en: 'class' },
      { ko: '도서관', en: 'library' },
      { ko: '수학', en: 'math' },
      { ko: '질문', en: 'question' },
      { ko: '발표', en: 'presentation' },
      { ko: '공부하다', en: 'study' },
    ],
    distractorsEn: ['kitchen', 'banana', 'ocean', 'shoes', 'purple', 'window', 'doctor', 'rainy'],
    distractorsKo: ['부엌', '바나나', '바다', '신발', '보라색', '창문', '의사', '겨울'],
  },
];
