// 섹션 7 — 고급 담화 (CEFR C1)
// 원어민 수준 뉘앙스와 추상 토론: 도치/강조 구문, 분사구문, 가정법, 헤지, 고급 연결어.

export const units = [
  {
    id: 's7u1',
    title: '추상과 개념',
    subtitle: '추상 주제 토론하기',
    icon: 'book',
    lessonCount: 5,
    pairs: [
      { ko: '자유란 결국 스스로 선택할 수 있는 능력이라고 생각해요.', en: "Freedom is ultimately the ability to choose for yourself.", alt: ["I think freedom is ultimately the ability to choose."] },
      { ko: '행복은 목적지가 아니라 여정이라고들 하죠.', en: "They say happiness is a journey, not a destination.", alt: ["Happiness is a journey, not a destination, they say."] },
      { ko: '성공이 무엇인지는 사람마다 다르게 정의해요.', en: "Everyone defines what success means in their own way.", alt: ["People define success differently from one another."] },
      { ko: '지식이 지금처럼 중요했던 적은 없었어요.', en: "Never has knowledge been more important than it is now.", alt: ["Knowledge has never been more important than now."] },
      { ko: '중요한 것은 돈이 아니라 마음의 평화예요.', en: "What matters is not money but peace of mind.", alt: ["It is peace of mind that matters, not money."] },
      { ko: '틀림없이 진정한 자유에는 책임이 따른다고 할 수 있죠.', en: "Arguably, true freedom always comes with responsibility.", alt: ["True freedom arguably comes with responsibility."] },
      { ko: '넓게 보면, 정의라는 개념은 문화마다 달라요.', en: "Broadly speaking, the concept of justice varies across cultures.", alt: ["Broadly speaking, justice varies from culture to culture."] },
      { ko: '지혜는 나이가 아니라 경험에서 나온다고 봐요.', en: "I believe wisdom comes from experience rather than age.", alt: ["Wisdom comes from experience, not from age."] },
      { ko: '우리는 종종 자유와 방종을 혼동하곤 해요.', en: "We often confuse freedom with a lack of restraint.", alt: ["People often confuse freedom with a lack of restraint."] },
      { ko: '겉으로 보이는 성공이 늘 진짜인 것은 아니에요.', en: "Visible success is not always what it seems.", alt: ["Success that looks real is not always genuine."] },
      { ko: '아마도 행복의 의미는 나이가 들수록 변하는 것 같아요.', en: "Presumably, the meaning of happiness changes as we age.", alt: ["The meaning of happiness presumably changes with age."] },
      { ko: '개념을 정의하는 일 자체가 하나의 철학이죠.', en: "Defining a concept is itself an act of philosophy.", alt: ["To define a concept is itself philosophical."] },
    ],
    words: [
      { ko: '자유', en: 'freedom' },
      { ko: '행복', en: 'happiness' },
      { ko: '성공', en: 'success' },
      { ko: '지혜', en: 'wisdom' },
      { ko: '개념', en: 'concept' },
      { ko: '정의', en: 'justice' },
      { ko: '책임', en: 'responsibility' },
      { ko: '거의 틀림없이', en: 'arguably' },
    ],
    distractorsEn: ['spoon', 'ladder', 'pigeon', 'sandal', 'vinegar', 'chimney', 'walnut', 'ribbon'],
    distractorsKo: ['숟가락', '사다리', '비둘기', '샌들', '식초', '굴뚝', '호두', '리본'],
  },
  {
    id: 's7u2',
    title: '설득과 협상',
    subtitle: '입장 조율과 설득',
    icon: 'chat',
    lessonCount: 5,
    pairs: [
      { ko: '제 제안을 다시 한번 고려해 주시면 좋겠습니다.', en: "I would appreciate it if you reconsidered my proposal.", alt: ["I'd appreciate it if you reconsidered my proposal."] },
      { ko: '가격을 낮춰 주시면 물량을 두 배로 늘리겠습니다.', en: "If you lower the price, we will double the order.", alt: ["We will double the order if you lower the price."] },
      { ko: '솔직히 말씀드리면, 그 조건은 받아들이기 어렵습니다.', en: "To be frank, those terms are difficult to accept.", alt: ["Frankly, those terms are hard for us to accept."] },
      { ko: '서로 조금씩 양보하면 합의에 도달할 수 있을 겁니다.', en: "If we each give a little, we can reach an agreement.", alt: ["We can reach an agreement if both sides compromise."] },
      { ko: '미리 알았더라면 다른 조건을 제시했을 거예요.', en: "Had I known earlier, I would have offered different terms.", alt: ["If I had known earlier, I would have offered different terms."] },
      { ko: '귀사의 입장은 이해하지만, 저희도 마진이 필요합니다.', en: "I understand your position, but we also need a margin.", alt: ["We understand your position, but we need a margin too."] },
      { ko: '이 조건이라면 양쪽 모두에게 이득이 될 겁니다.', en: "Under these terms, both sides would clearly benefit.", alt: ["These terms would clearly benefit both sides."] },
      { ko: '결정을 내리시기 전에 장단점을 따져 보시죠.', en: "Let's weigh the pros and cons before you decide.", alt: ["Before deciding, let us weigh the pros and cons."] },
      { ko: '저희가 한 발 물러설 테니, 귀사도 양보해 주시죠.', en: "We will take a step back, so please meet us halfway.", alt: ["We'll step back, so please meet us halfway."] },
      { ko: '저희는 품질을 중시하는 반면, 귀사는 속도를 중시하시죠.', en: "We value quality, whereas your company values speed.", alt: ["We focus on quality, whereas you focus on speed."] },
      { ko: '오늘 계약하시면 배송비는 저희가 부담하겠습니다.', en: "If you sign today, we will cover the shipping cost.", alt: ["We will cover the shipping cost if you sign today."] },
      { ko: '이 정도면 서로에게 공정한 타협안이라고 생각합니다.', en: "I believe this is a fair compromise for both of us.", alt: ["I think this is a fair compromise for everyone."] },
    ],
    words: [
      { ko: '제안', en: 'proposal' },
      { ko: '협상', en: 'negotiation' },
      { ko: '타협', en: 'compromise' },
      { ko: '조건', en: 'terms' },
      { ko: '양보하다', en: 'concede' },
      { ko: '설득하다', en: 'persuade' },
      { ko: '합의', en: 'agreement' },
      { ko: '이득', en: 'benefit' },
    ],
    distractorsEn: ['blanket', 'turtle', 'pepper', 'violin', 'meadow', 'anchor', 'cactus', 'lantern'],
    distractorsKo: ['담요', '거북이', '후추', '바이올린', '초원', '닻줄', '선인장', '랜턴'],
  },
  {
    id: 's7u3',
    title: '사회와 이슈',
    subtitle: '사회 문제 논하기',
    icon: 'chart',
    lessonCount: 5,
    pairs: [
      { ko: '기후 변화는 더 이상 미래의 문제가 아니에요.', en: "Climate change is no longer a problem of the future.", alt: ["Climate change is no longer a future problem."] },
      { ko: '재생 에너지에 대한 투자가 시급하다고 봅니다.', en: "I would argue that investment in renewable energy is urgent.", alt: ["Investment in renewable energy is urgently needed."] },
      { ko: '기술은 삶을 편하게 했지만, 그럼에도 대가가 따랐죠.', en: "Technology made life easier; nevertheless, it came at a cost.", alt: ["Technology made life easier, but it came at a cost."] },
      { ko: '기성세대는 안정을 중시하는 반면, 젊은 세대는 유연함을 원해요.', en: "Older generations value stability, whereas younger ones want flexibility.", alt: ["Older people value stability, whereas the young want flexibility."] },
      { ko: '소셜 미디어가 여론을 형성하는 방식은 우려스러워요.', en: "The way social media shapes public opinion is worrying.", alt: ["How social media shapes public opinion is worrying."] },
      { ko: '아마도 인공지능이 많은 직업을 바꿔 놓을 거예요.', en: "Presumably, artificial intelligence will transform many of our jobs.", alt: ["Artificial intelligence will presumably transform many jobs."] },
      { ko: '경제 성장과 환경 보호는 균형을 이뤄야 합니다.', en: "Economic growth must be balanced with protecting the environment.", alt: ["We must balance economic growth with environmental protection."] },
      { ko: '통계를 고려하면, 상황은 생각보다 심각합니다.', en: "Considering the statistics, the situation is worse than we thought.", alt: ["Given the statistics, the situation is worse than expected."] },
      { ko: '문제는 인식이 아니라 실천이 부족하다는 거예요.', en: "The problem is not awareness but a lack of action.", alt: ["What we lack is not awareness but action."] },
      { ko: '주거비 상승이 세대 갈등을 부추기고 있어요.', en: "Rising housing costs are fueling tension between generations.", alt: ["Rising housing costs are deepening the generational divide."] },
      { ko: '한 사회의 성숙도는 약자를 대하는 태도에서 드러나죠.', en: "A society reveals its maturity in how it treats the vulnerable.", alt: ["How a society treats the vulnerable reveals its maturity."] },
      { ko: '변화가 지금처럼 빨랐던 적은 없었습니다.', en: "Rarely has change moved as fast as it does today.", alt: ["Change has rarely moved as fast as it does today."] },
    ],
    words: [
      { ko: '기후', en: 'climate' },
      { ko: '세대', en: 'generation' },
      { ko: '여론', en: 'public opinion' },
      { ko: '지속 가능한', en: 'sustainable' },
      { ko: '불평등', en: 'inequality' },
      { ko: '정책', en: 'policy' },
      { ko: '그럼에도', en: 'nevertheless' },
      { ko: '~인 반면', en: 'whereas' },
    ],
    distractorsEn: ['muffin', 'sailor', 'crayon', 'harbor', 'tulip', 'wallet', 'donkey', 'mirror'],
    distractorsKo: ['머핀', '선원', '크레용', '항구', '튤립', '지갑', '당나귀', '거울'],
  },
  {
    id: 's7u4',
    title: '미디어 비평',
    subtitle: '작품 분석과 해석',
    icon: 'star',
    lessonCount: 5,
    pairs: [
      { ko: '그 영화는 몰입감 있었지만 결말은 아쉬웠어요.', en: "The film was gripping, though the ending fell flat.", alt: ["The film was gripping, but the ending fell flat."] },
      { ko: '주인공의 심리 묘사가 놀라울 만큼 섬세했어요.', en: "The portrayal of the main character was remarkably subtle.", alt: ["The main character was portrayed with remarkable subtlety."] },
      { ko: '그 소설은 상실이라는 주제를 절제된 방식으로 다뤄요.', en: "The novel explores the theme of loss with restraint.", alt: ["The novel handles the theme of loss with restraint."] },
      { ko: '비평가들은 호평했지만, 저는 과대평가됐다고 봐요.', en: "Critics praised it, but I find it rather overrated.", alt: ["Critics loved it, but I think it is overrated."] },
      { ko: '연출은 훌륭했는데 각본이 그걸 못 따라갔어요.', en: "The direction was superb, but the script fell short.", alt: ["The directing was superb, but the writing fell short."] },
      { ko: '중반부의 전개가 다소 늘어진다는 느낌이었어요.', en: "The pacing felt somewhat slow in the middle section.", alt: ["The middle section felt somewhat slow in pacing."] },
      { ko: '결말은 여러 갈래로 해석될 여지를 남겨요.', en: "The ending leaves plenty of room for interpretation.", alt: ["The ending is open to multiple interpretations."] },
      { ko: '그 장면은 뻔한 설정인데도 신선하게 느껴졌어요.', en: "The scene felt fresh despite its familiar setup.", alt: ["Despite its familiar setup, the scene felt fresh."] },
      { ko: '촬영이 이야기의 쓸쓸한 분위기를 완벽하게 담아냈어요.', en: "The cinematography perfectly captures the story's bleak mood.", alt: ["The cinematography captures the bleak mood of the story."] },
      { ko: '등장인물이 평면적이라 감정 이입이 어려웠어요.', en: "The characters were so flat that I couldn't relate.", alt: ["The characters were too flat for me to relate to."] },
      { ko: '이 작품을 특별하게 만드는 것은 바로 그 여운이에요.', en: "What makes this work special is the feeling it leaves.", alt: ["It is the lingering feeling that makes this work special."] },
      { ko: '원작을 읽고 나서 보면 해석이 완전히 달라져요.', en: "Reading the original first completely changes your interpretation.", alt: ["Your interpretation changes completely once you read the original."] },
    ],
    words: [
      { ko: '비평', en: 'criticism' },
      { ko: '해석', en: 'interpretation' },
      { ko: '연출', en: 'direction' },
      { ko: '각본', en: 'script' },
      { ko: '몰입감 있는', en: 'gripping' },
      { ko: '과대평가된', en: 'overrated' },
      { ko: '섬세한', en: 'subtle' },
      { ko: '진부한 표현', en: 'cliche' },
    ],
    distractorsEn: ['pumpkin', 'bicycle', 'sparrow', 'kettle', 'glacier', 'napkin', 'pebble', 'trumpet'],
    distractorsKo: ['호박', '자전거', '참새', '주전자', '빙하', '냅킨', '조약돌', '트럼펫'],
  },
  {
    id: 's7u5',
    title: '유머와 반어법',
    subtitle: '재치와 가벼운 농담',
    icon: 'bolt',
    lessonCount: 5,
    pairs: [
      { ko: '월요일 아침이라니, 정말 딱 바라던 거였네요.', en: "A Monday morning, just what I always wanted.", alt: ["Monday morning, exactly what I always wanted."] },
      { ko: '또 비라니, 날씨가 우리를 참 아껴 주네요.', en: "Rain again? The weather really spoils us here.", alt: ["Rain again? The weather is really spoiling us."] },
      { ko: '농담이에요. 너무 진지하게 받아들이지 마세요.', en: "I am just kidding, so don't take it seriously.", alt: ["Just kidding, don't take it too seriously."] },
      { ko: '그의 말은 문자 그대로가 아니라 반어법이었어요.', en: "He was being ironic, not speaking literally.", alt: ["He meant it ironically, not literally."] },
      { ko: '와, 정말 형편없는 농담인데 웃음이 나오네요.', en: "Wow, that joke was terrible, yet I am laughing.", alt: ["That joke was terrible, yet somehow I am laughing."] },
      { ko: '오늘도 야근이라니, 꿈이 다 이루어지네요.', en: "Working late again tonight? Dreams really do come true.", alt: ["Overtime again tonight? Dreams really do come true."] },
      { ko: '그렇게 겸손하시다니, 보기 드문 재능이네요.', en: "Such modesty! That is truly a rare talent.", alt: ["So modest! That is truly a rare talent."] },
      { ko: '그 유머는 미묘해서 다들 한 박자 늦게 웃었어요.', en: "The humor was so subtle that everyone laughed late.", alt: ["The joke was so subtle that everyone laughed late."] },
      { ko: '진심이 아니라 비꼬는 말이라는 걸 눈치챘어요.', en: "I could tell he was being sarcastic, not sincere.", alt: ["I noticed he was being sarcastic, not sincere."] },
      { ko: '재치 있는 대답이 어색한 분위기를 살렸어요.', en: "A witty reply saved the awkward moment.", alt: ["The awkward moment was saved by a witty reply."] },
      { ko: '완벽한 계획이네요. 도대체 뭐가 잘못될 수 있겠어요?', en: "What a perfect plan. What could possibly go wrong?", alt: ["A perfect plan. What could possibly go wrong?"] },
      { ko: '유머 감각은 사실 지능의 표시라고들 해요.', en: "They say a sense of humor signals real intelligence.", alt: ["A sense of humor is said to signal intelligence."] },
    ],
    words: [
      { ko: '반어법', en: 'irony' },
      { ko: '비꼬는', en: 'sarcastic' },
      { ko: '재치 있는', en: 'witty' },
      { ko: '농담', en: 'joke' },
      { ko: '말장난', en: 'pun' },
      { ko: '웃음', en: 'laughter' },
      { ko: '과장', en: 'exaggeration' },
      { ko: '눈치채다', en: 'notice' },
    ],
    distractorsEn: ['carrot', 'stadium', 'jungle', 'candle', 'saddle', 'pillow', 'magnet', 'faucet'],
    distractorsKo: ['당근', '경기장', '정글', '양초', '안장', '베개', '자석', '수도꼭지'],
  },
  {
    id: 's7u6',
    title: '원어민 마스터',
    subtitle: '자연스러운 구어체',
    icon: 'crown',
    lessonCount: 5,
    pairs: [
      { ko: '있잖아, 나 사실 그 일 그만둘까 생각 중이야.', en: "You know, I am actually thinking about quitting that job.", alt: ["You know, I'm actually thinking of quitting that job."] },
      { ko: '내 말은, 그 문제가 그렇게 간단하지 않다는 거야.', en: "I mean, the problem is just not that simple.", alt: ["I mean, it's just not that simple."] },
      { ko: '솔직히 말해서, 나라면 그렇게는 안 했을 거야.', en: "To be honest, I wouldn't have done it that way.", alt: ["Honestly, I would not have done it that way."] },
      { ko: '지금 막 나가려던 참이었어.', en: "I was just about to head out.", alt: ["I was just about to leave."] },
      { ko: '어차피 할 거면 제대로 하는 게 낫지.', en: "If you are going to do it, do it properly.", alt: ["If you're going to do it, do it right."] },
      { ko: '신기하네, 나도 막 그 얘기 꺼내려던 참이었어.', en: "Funny, I was just about to bring that up.", alt: ["I was actually just about to mention that."] },
      { ko: '뭐랄까, 그 사람 첫인상이 좀 묘했어.', en: "How should I put it? He made an odd first impression.", alt: ["How do I put it? He seemed a bit odd."] },
      { ko: '아무튼, 결론은 우리가 좀 더 기다려야 한다는 거야.', en: "Anyway, the bottom line is we have to wait longer.", alt: ["Anyway, the point is we need to wait longer."] },
      { ko: '그게 말이 쉽지, 실제로는 훨씬 어렵다니까.', en: "That is easier said than done, believe me.", alt: ["It's easier said than done, trust me."] },
      { ko: '네 말도 일리는 있는데, 난 여전히 확신이 안 서.', en: "Fair point, but I am still not fully convinced.", alt: ["You have a point, but I'm still not convinced."] },
      { ko: '별일 아니니까 너무 신경 쓰지 마.', en: "It is not a big deal, so don't stress over it.", alt: ["It's no big deal, so don't stress about it."] },
      { ko: '오늘은 여기까지 하고, 나머지는 내일 이어서 하자.', en: "Let's call it a day and pick this up tomorrow.", alt: ["Let us call it a day and continue tomorrow."] },
    ],
    words: [
      { ko: '있잖아', en: 'you know' },
      { ko: '아무튼', en: 'anyway' },
      { ko: '요점', en: 'bottom line' },
      { ko: '확신하는', en: 'convinced' },
      { ko: '제대로', en: 'properly' },
      { ko: '그만두다', en: 'quit' },
      { ko: '솔직히', en: 'honestly' },
      { ko: '일리 있는 지적', en: 'fair point' },
    ],
    distractorsEn: ['zebra', 'onion', 'forest', 'hammer', 'rocket', 'castle', 'noodle', 'ferry'],
    distractorsKo: ['얼룩말', '양파', '망치', '로켓', '성곽', '국수', '나룻배', '단추'],
  },
];
