// 섹션 4 — 소통의 기술 (CEFR B1)
// 문법: 현재완료, 비교급/최상급, should/have to, 간접의문문, 관계대명사 기초
export const units = [
  {
    id: 's4u1',
    title: '의견 말하기',
    subtitle: '생각을 나눠 봐요',
    icon: 'chat',
    lessonCount: 5,
    pairs: [
      { ko: '제 생각에는 이 영화가 정말 재미있어요.', en: "I think this movie is really fun.", alt: ["In my opinion, this movie is really fun."] },
      { ko: '저는 당신 의견에 동의해요.', en: "I agree with your opinion.", alt: ["I agree with you."] },
      { ko: '미안하지만 저는 동의하지 않아요.', en: "Sorry, but I do not agree.", alt: ["Sorry, but I disagree.", "I am sorry, but I do not agree."] },
      { ko: '당신은 그것에 대해 어떻게 생각하세요?', en: "What do you think about it?", alt: ["What do you think?"] },
      { ko: '제 의견으로는 그 계획이 너무 위험해요.', en: "In my opinion, the plan is too risky.", alt: ["I think the plan is too risky."] },
      { ko: '좋은 지적이에요, 하지만 저는 확신이 없어요.', en: "That is a good point, but I am not sure.", alt: ["That's a good point, but I'm not sure."] },
      { ko: '저는 그것이 좋은 생각이라고 믿어요.', en: "I believe that is a good idea.", alt: ["I believe it is a good idea.", "I believe that's a good idea."] },
      { ko: '솔직히 말하면 저는 그 색이 마음에 들지 않아요.', en: "To be honest, I do not like that color.", alt: ["To be honest, I don't like that color.", "Honestly, I do not like that color."] },
      { ko: '왜 그렇게 생각하는지 말해 줄 수 있나요?', en: "Can you tell me why you think so?", alt: ["Could you tell me why you think so?"] },
      { ko: '어느 정도는 당신 말이 맞아요.', en: "You are right to some degree.", alt: ["You're right to some degree.", "You are partly right."] },
      { ko: '우리는 서로 다른 의견을 가질 수 있어요.', en: "We can have different opinions from each other.", alt: ["We can have different opinions."] },
      { ko: '그 문제에 대한 당신의 의견을 듣고 싶어요.', en: "I want to hear your opinion about that issue.", alt: ["I would like to hear your opinion about that issue."] },
    ],
    words: [
      { ko: '의견', en: 'opinion' },
      { ko: '동의하다', en: 'agree' },
      { ko: '반대하다', en: 'disagree' },
      { ko: '믿다', en: 'believe' },
      { ko: '요점', en: 'point' },
      { ko: '확신하는', en: 'sure' },
      { ko: '솔직한', en: 'honest' },
      { ko: '쟁점', en: 'issue' },
    ],
    distractorsEn: ['window', 'kitchen', 'yellow', 'bridge', 'cloud', 'pencil', 'garden', 'river'],
    distractorsKo: ['창문', '부엌', '노란색', '다리', '구름', '연필', '정원', '강'],
  },
  {
    id: 's4u2',
    title: '경험 나누기',
    subtitle: '경험을 이야기해요',
    icon: 'star',
    lessonCount: 5,
    pairs: [
      { ko: '해외에 가 본 적이 있나요?', en: "Have you ever been abroad?", alt: ["Have you ever traveled abroad?"] },
      { ko: '저는 파리에 두 번 가 봤어요.', en: "I have been to Paris twice.", alt: ["I've been to Paris twice."] },
      { ko: '저는 아직 초밥을 먹어 본 적이 없어요.', en: "I have never eaten sushi before.", alt: ["I've never eaten sushi before.", "I have never tried sushi before."] },
      { ko: '말을 타 본 적이 있나요?', en: "Have you ever ridden a horse?", alt: [] },
      { ko: '저는 그 책을 세 번 읽었어요.', en: "I have read that book three times.", alt: ["I've read that book three times."] },
      { ko: '그는 유명한 가수를 만난 적이 있어요.', en: "He has met a famous singer before.", alt: ["He's met a famous singer before."] },
      { ko: '우리는 그 도시에 산 적이 있어요.', en: "We have lived in that city before.", alt: ["We've lived in that city before."] },
      { ko: '저는 한 번도 눈을 본 적이 없어요.', en: "I have never seen snow in my life.", alt: ["I've never seen snow in my life."] },
      { ko: '지금까지 가장 좋았던 여행은 무엇이었나요?', en: "What was your best trip so far?", alt: ["What has been your best trip so far?"] },
      { ko: '그녀는 방금 저녁 식사를 끝냈어요.', en: "She has just finished her dinner.", alt: ["She's just finished her dinner.", "She just finished her dinner."] },
      { ko: '저는 이 노래를 전에 들어 본 적이 있어요.', en: "I have heard this song before.", alt: ["I've heard this song before."] },
      { ko: '당신은 얼마나 오래 여기에 살았나요?', en: "How long have you lived here?", alt: [] },
    ],
    words: [
      { ko: '경험', en: 'experience' },
      { ko: '여행', en: 'trip' },
      { ko: '해외', en: 'abroad' },
      { ko: '결코', en: 'never' },
      { ko: '이미', en: 'already' },
      { ko: '아직', en: 'yet' },
      { ko: '방금', en: 'just' },
      { ko: '유명한', en: 'famous' },
    ],
    distractorsEn: ['banana', 'clock', 'purple', 'street', 'flower', 'winter', 'teacher', 'market'],
    distractorsKo: ['바나나', '시계', '보라색', '거리', '꽃', '겨울', '선생님', '시장'],
  },
  {
    id: 's4u3',
    title: '비교와 선택',
    subtitle: '더 나은 것 고르기',
    icon: 'chart',
    lessonCount: 5,
    pairs: [
      { ko: '이 가방이 저 가방보다 더 싸요.', en: "This bag is cheaper than that one.", alt: [] },
      { ko: '저는 커피보다 차를 더 좋아해요.', en: "I prefer tea to coffee.", alt: ["I like tea more than coffee.", "I like tea better than coffee."] },
      { ko: '오늘이 어제보다 훨씬 더 따뜻해요.', en: "Today is much warmer than yesterday.", alt: [] },
      { ko: '이곳이 이 도시에서 가장 좋은 식당이에요.', en: "This is the best restaurant in this city.", alt: ["This is the best restaurant in the city."] },
      { ko: '어느 것이 더 마음에 드세요?', en: "Which one do you like more?", alt: ["Which one do you like better?"] },
      { ko: '기차가 버스보다 더 빨라요.', en: "The train is faster than the bus.", alt: [] },
      { ko: '저는 시끄러운 곳보다 조용한 곳을 더 좋아해요.', en: "I prefer quiet places to noisy places.", alt: ["I like quiet places more than noisy places."] },
      { ko: '이 문제가 훨씬 더 어려워요.', en: "This problem is much harder.", alt: ["This problem is much more difficult."] },
      { ko: '그것이 우리에게 가장 중요한 일이에요.', en: "That is the most important thing for us.", alt: ["It is the most important thing for us.", "That's the most important thing for us."] },
      { ko: '검은색 재킷과 파란색 재킷 중 어느 것이 더 나아요?', en: "Which is better, the black jacket or the blue one?", alt: [] },
      { ko: '저라면 더 작은 차를 선택하겠어요.', en: "I would choose the smaller car.", alt: ["I'd choose the smaller car."] },
      { ko: '가격이 품질보다 더 중요한가요?', en: "Is price more important than quality?", alt: [] },
    ],
    words: [
      { ko: '비교하다', en: 'compare' },
      { ko: '선택하다', en: 'choose' },
      { ko: '선호하다', en: 'prefer' },
      { ko: '더 싼', en: 'cheaper' },
      { ko: '더 나은', en: 'better' },
      { ko: '최고의', en: 'best' },
      { ko: '품질', en: 'quality' },
      { ko: '가격', en: 'price' },
    ],
    distractorsEn: ['spoon', 'rabbit', 'cloudy', 'silver', 'mountain', 'letter', 'sunny', 'bottle'],
    distractorsKo: ['숟가락', '토끼', '흐린', '은색', '산', '편지', '맑은', '병'],
  },
  {
    id: 's4u4',
    title: '전화와 메시지',
    subtitle: '전화로 소통해요',
    icon: 'bolt',
    lessonCount: 5,
    pairs: [
      { ko: '여보세요, 지수와 통화할 수 있을까요?', en: "Hello, may I speak to Jisu, please?", alt: ["Hello, can I speak to Jisu, please?", "Hello, could I speak to Jisu, please?"] },
      { ko: '지금 그는 자리에 없어요.', en: "He is not here right now.", alt: ["He's not here right now.", "He is not at his desk right now."] },
      { ko: '메시지를 남기시겠어요?', en: "Would you like to leave a message?", alt: ["Do you want to leave a message?"] },
      { ko: '제가 나중에 다시 전화할게요.', en: "I will call you back later.", alt: ["I'll call you back later."] },
      { ko: '전화 주셔서 감사합니다.', en: "Thank you for calling me.", alt: ["Thanks for calling me."] },
      { ko: '죄송하지만 전화를 잘못 거셨어요.', en: "Sorry, you have the wrong number.", alt: ["I am sorry, you have the wrong number.", "I'm sorry, you have the wrong number."] },
      { ko: '좀 더 크게 말씀해 주시겠어요?', en: "Could you speak a little louder, please?", alt: ["Can you speak a little louder, please?"] },
      { ko: '잠시만 기다려 주세요, 연결해 드릴게요.', en: "Please hold on, I will connect you.", alt: ["Please hold on, I'll connect you."] },
      { ko: '문자 메시지를 보내 주실 수 있나요?', en: "Can you send me a text message?", alt: ["Could you send me a text message?"] },
      { ko: '그녀는 지금 다른 전화를 받고 있어요.', en: "She is on another call right now.", alt: ["She's on another call right now."] },
      { ko: '전화번호를 알려 주시겠어요?', en: "Could you give me your phone number?", alt: ["Can you give me your phone number?"] },
      { ko: '통화 가능할 때 저에게 다시 전화해 주세요.', en: "Please call me back when you are free.", alt: ["Please call me back when you're free."] },
    ],
    words: [
      { ko: '전화', en: 'phone' },
      { ko: '메시지', en: 'message' },
      { ko: '문자', en: 'text' },
      { ko: '번호', en: 'number' },
      { ko: '남기다', en: 'leave' },
      { ko: '연결하다', en: 'connect' },
      { ko: '잘못된', en: 'wrong' },
      { ko: '나중에', en: 'later' },
    ],
    distractorsEn: ['cheese', 'tiger', 'piano', 'beach', 'candle', 'forest', 'grape', 'stone'],
    distractorsKo: ['치즈', '호랑이', '피아노', '해변', '양초', '숲', '포도', '돌'],
  },
  {
    id: 's4u5',
    title: '뉴스와 사회',
    subtitle: '세상 소식 나누기',
    icon: 'book',
    lessonCount: 5,
    pairs: [
      { ko: '오늘 아침 뉴스 봤어요?', en: "Did you watch the news this morning?", alt: ["Did you see the news this morning?"] },
      { ko: '그 기사에 따르면 물가가 오르고 있대요.', en: "According to the article, prices are going up.", alt: ["According to the article, prices are rising."] },
      { ko: '점점 더 많은 사람들이 자전거로 출근해요.', en: "More and more people ride bikes to work.", alt: [] },
      { ko: '그 소식을 들었을 때 정말 놀랐어요.', en: "I was really surprised when I heard the news.", alt: ["I was so surprised when I heard the news."] },
      { ko: '사람들이 그 새로운 법에 대해 이야기하고 있어요.', en: "People are talking about the new law.", alt: [] },
      { ko: '당신은 그 문제에 대해 어떻게 생각하세요?', en: "What do you think about that problem?", alt: ["What do you think about that issue?"] },
      { ko: '인터넷에서 그 이야기를 읽었어요.', en: "I read that story on the internet.", alt: [] },
      { ko: '많은 사람들이 환경을 걱정하고 있어요.', en: "Many people are worried about the environment.", alt: ["A lot of people are worried about the environment."] },
      { ko: '정부는 새로운 계획을 발표했어요.', en: "The government announced a new plan.", alt: [] },
      { ko: '모든 뉴스를 믿을 수는 없어요.', en: "You cannot believe all the news.", alt: ["You can't believe all the news."] },
      { ko: '그 도시의 날씨가 기록을 깼다고 해요.', en: "They say the weather in that city broke a record.", alt: [] },
      { ko: '우리는 어젯밤 그 선거에 대해 이야기했어요.', en: "We talked about the election last night.", alt: [] },
    ],
    words: [
      { ko: '뉴스', en: 'news' },
      { ko: '기사', en: 'article' },
      { ko: '정부', en: 'government' },
      { ko: '법', en: 'law' },
      { ko: '환경', en: 'environment' },
      { ko: '선거', en: 'election' },
      { ko: '사회', en: 'society' },
      { ko: '기자', en: 'reporter' },
    ],
    distractorsEn: ['butter', 'monkey', 'ocean', 'guitar', 'ladder', 'cherry', 'pillow', 'shoes'],
    distractorsKo: ['버터', '원숭이', '바다', '기타', '사다리', '체리', '베개', '신발'],
  },
  {
    id: 's4u6',
    title: '조언하기',
    subtitle: '따뜻한 한마디',
    icon: 'heart',
    lessonCount: 5,
    pairs: [
      { ko: '너는 오늘 밤 일찍 자는 게 좋겠어.', en: "You should go to bed early tonight.", alt: [] },
      { ko: '의사에게 가 보는 게 어때?', en: "Why don't you go see a doctor?", alt: ["Why don't you see a doctor?", "You should go see a doctor."] },
      { ko: '너무 걱정하지 않는 게 좋아.', en: "You should not worry too much.", alt: ["You shouldn't worry too much."] },
      { ko: '조언 좀 해 줄 수 있어?', en: "Can you give me some advice?", alt: ["Could you give me some advice?"] },
      { ko: '나라면 그에게 진실을 말하겠어.', en: "If I were you, I would tell him the truth.", alt: ["I would tell him the truth."] },
      { ko: '너는 휴식이 필요한 것 같아.', en: "I think you need some rest.", alt: ["I think you need a break."] },
      { ko: '매일 물을 더 많이 마셔야 해.', en: "You have to drink more water every day.", alt: ["You should drink more water every day."] },
      { ko: '먼저 그녀에게 사과하는 게 어때?', en: "Why don't you apologize to her first?", alt: ["You should apologize to her first."] },
      { ko: '도움을 요청하는 것을 두려워하지 마.', en: "Do not be afraid to ask for help.", alt: ["Don't be afraid to ask for help."] },
      { ko: '스트레스를 받을 때는 산책을 해 봐.', en: "Try taking a walk when you feel stressed.", alt: ["Take a walk when you feel stressed."] },
      { ko: '그 문제에 대해 부모님과 이야기해 보는 게 좋겠어.', en: "You should talk to your parents about the problem.", alt: ["You should talk with your parents about the problem."] },
      { ko: '나는 항상 네 편이라는 걸 기억해.', en: "Remember that I am always on your side.", alt: ["Remember that I'm always on your side."] },
    ],
    words: [
      { ko: '조언', en: 'advice' },
      { ko: '걱정하다', en: 'worry' },
      { ko: '휴식', en: 'rest' },
      { ko: '사과하다', en: 'apologize' },
      { ko: '진실', en: 'truth' },
      { ko: '건강', en: 'health' },
      { ko: '습관', en: 'habit' },
      { ko: '스트레스', en: 'stress' },
    ],
    distractorsEn: ['camera', 'jungle', 'pocket', 'lemon', 'carpet', 'turtle', 'violin', 'basket'],
    distractorsKo: ['카메라', '정글', '주머니', '레몬', '카펫', '거북이', '바이올린', '바구니'],
  },
];
