// 섹션 2 — CEFR A1+ 「생활 영어」
// 문법: 현재시제, can/can't, 의문사 의문문, how much/many, 전치사

export const units = [
  {
    id: 's2u1',
    title: '쇼핑',
    subtitle: '물건 사고 계산하기',
    icon: 'shop',
    lessonCount: 5,
    pairs: [
      { ko: '이 셔츠는 얼마예요?', en: "How much is this shirt?", alt: ["How much does this shirt cost?"] },
      { ko: '그것은 십 달러예요.', en: "It is ten dollars.", alt: ["That is ten dollars.", "It costs ten dollars."] },
      { ko: '더 작은 사이즈 있어요?', en: "Do you have a smaller size?", alt: ["Do you have this in a smaller size?"] },
      { ko: '이거 입어 봐도 돼요?', en: "Can I try this on?", alt: ["May I try this on?"] },
      { ko: '카드로 계산할 수 있어요?', en: "Can I pay with a card?", alt: ["Can I pay by card?"] },
      { ko: '이것을 환불하고 싶어요.', en: "I want to return this.", alt: ["I would like to return this.", "I'd like to return this."] },
      { ko: '영수증 가지고 계세요?', en: "Do you have the receipt?", alt: ["Do you have a receipt?"] },
      { ko: '그것은 너무 비싸요.', en: "It is too expensive.", alt: ["That is too expensive.", "This is too expensive."] },
      { ko: '저 신발은 세일 중이에요.', en: "Those shoes are on sale.", alt: ["The shoes are on sale."] },
      { ko: '봉투 필요하세요?', en: "Do you need a bag?", alt: ["Would you like a bag?"] },
      { ko: '그냥 구경하는 중이에요.', en: "I am just looking, thanks.", alt: ["I'm just looking, thanks."] },
      { ko: '탈의실은 어디에 있어요?', en: "Where is the fitting room?", alt: ["Where's the fitting room?"] },
    ],
    words: [
      { ko: '가격', en: 'price' },
      { ko: '돈', en: 'money' },
      { ko: '셔츠', en: 'shirt' },
      { ko: '신발', en: 'shoes' },
      { ko: '사이즈', en: 'size' },
      { ko: '영수증', en: 'receipt' },
      { ko: '세일', en: 'sale' },
      { ko: '환불', en: 'refund' },
    ],
    distractorsEn: ['window', 'kitchen', 'teacher', 'rainy', 'guitar', 'monday', 'bridge', 'lemon'],
    distractorsKo: ['창문', '부엌', '선생님', '월요일', '기타', '다리', '레몬', '구름'],
  },
  {
    id: 's2u2',
    title: '시간과 날짜',
    subtitle: '시간 묻고 약속 잡기',
    icon: 'chart',
    lessonCount: 5,
    pairs: [
      { ko: '지금 몇 시예요?', en: "What time is it now?", alt: ["What time is it?"] },
      { ko: '세 시 삼십 분이에요.', en: "It is three thirty.", alt: ["It's three thirty now.", "It is half past three."] },
      { ko: '오늘은 무슨 요일이에요?', en: "What day is it today?", alt: ["What day is today?"] },
      { ko: '제 생일은 금요일이에요.', en: "My birthday is on Friday.", alt: ["My birthday is Friday."] },
      { ko: '회의는 두 시에 시작해요.', en: "The meeting starts at two.", alt: ["The meeting begins at two."] },
      { ko: '월요일에 시간 있어요?', en: "Are you free on Monday?", alt: ["Do you have time on Monday?"] },
      { ko: '점심에 만날 수 있어요?', en: "Can we meet for lunch?", alt: ["Can we meet at lunch?"] },
      { ko: '저는 일곱 시에 일어나요.', en: "I get up at seven.", alt: ["I wake up at seven."] },
      { ko: '영화는 오늘 밤 아홉 시에 시작해요.', en: "The movie starts at nine tonight.", alt: ["The movie begins at nine tonight."] },
      { ko: '주말에 뭐 해요?', en: "What do you do on weekends?", alt: ["What do you do on the weekend?"] },
      { ko: '늦어서 미안해요.', en: "Sorry I am late.", alt: ["I am sorry I am late."] },
      { ko: '내일 아침에 전화할게요.', en: "I will call you tomorrow morning.", alt: ["I'll call you tomorrow morning."] },
    ],
    words: [
      { ko: '시간', en: 'time' },
      { ko: '요일', en: 'day' },
      { ko: '주', en: 'week' },
      { ko: '아침', en: 'morning' },
      { ko: '오후', en: 'afternoon' },
      { ko: '저녁', en: 'evening' },
      { ko: '약속', en: 'appointment' },
      { ko: '달력', en: 'calendar' },
    ],
    distractorsEn: ['apple', 'shoes', 'river', 'yellow', 'doctor', 'swim', 'cloud', 'chair'],
    distractorsKo: ['사과', '신발', '강', '노란색', '의사', '수영', '구름', '의자'],
  },
  {
    id: 's2u3',
    title: '날씨',
    subtitle: '날씨와 계절 표현',
    icon: 'sun',
    lessonCount: 5,
    pairs: [
      { ko: '오늘 날씨 어때요?', en: "How is the weather today?", alt: ["How's the weather today?"] },
      { ko: '밖에 비가 오고 있어요.', en: "It is raining outside.", alt: ["It's raining outside right now."] },
      { ko: '우산 가져가세요.', en: "Take your umbrella with you.", alt: ["Please take your umbrella."] },
      { ko: '오늘은 정말 춥네요.', en: "It is really cold today.", alt: ["It's really cold today."] },
      { ko: '여름에는 아주 더워요.', en: "It is very hot in summer.", alt: ["It's very hot in the summer."] },
      { ko: '저는 봄을 가장 좋아해요.', en: "I like spring the best.", alt: ["Spring is my favorite season."] },
      { ko: '내일은 눈이 올 거예요.', en: "It will snow tomorrow.", alt: ["It's going to snow tomorrow."] },
      { ko: '따뜻한 코트를 입으세요.', en: "Wear a warm coat.", alt: ["Put on a warm coat."] },
      { ko: '하늘에 구름이 없어요.', en: "There are no clouds in the sky.", alt: ["The sky has no clouds."] },
      { ko: '밖에 바람이 많이 불어요.', en: "It is very windy outside.", alt: ["It's very windy outside."] },
      { ko: '장마철에는 매일 비가 와요.', en: "It rains every day in the rainy season.", alt: ["It rains daily in the rainy season."] },
      { ko: '겨울에는 눈사람을 만들어요.', en: "We make a snowman in winter.", alt: ["We build a snowman in winter."] },
    ],
    words: [
      { ko: '날씨', en: 'weather' },
      { ko: '비', en: 'rain' },
      { ko: '눈', en: 'snow' },
      { ko: '바람', en: 'wind' },
      { ko: '구름', en: 'cloud' },
      { ko: '우산', en: 'umbrella' },
      { ko: '여름', en: 'summer' },
      { ko: '겨울', en: 'winter' },
    ],
    distractorsEn: ['banana', 'pencil', 'nurse', 'train', 'happy', 'table', 'green', 'music'],
    distractorsKo: ['바나나', '연필', '간호사', '기차', '행복한', '탁자', '초록색', '음악'],
  },
  {
    id: 's2u4',
    title: '취미',
    subtitle: '좋아하는 것 말하기',
    icon: 'star',
    lessonCount: 5,
    pairs: [
      { ko: '취미가 뭐예요?', en: "What are your hobbies?", alt: ["What is your hobby?"] },
      { ko: '저는 기타 치는 것을 좋아해요.', en: "I like playing the guitar.", alt: ["I like to play the guitar."] },
      { ko: '그는 주말마다 축구를 해요.', en: "He plays soccer every weekend.", alt: ["He plays soccer on weekends."] },
      { ko: '저는 항상 아침에 책을 읽어요.', en: "I always read in the morning.", alt: ["I always read books in the morning."] },
      { ko: '우리는 가끔 영화를 봐요.', en: "We sometimes watch a movie.", alt: ["Sometimes we watch a movie."] },
      { ko: '수영 잘할 수 있어요?', en: "Can you swim well?", alt: ["Are you good at swimming?"] },
      { ko: '저는 요리를 잘 못해요.', en: "I cannot cook very well.", alt: ["I can't cook very well."] },
      { ko: '그녀는 매일 사진을 찍어요.', en: "She takes pictures every day.", alt: ["She takes photos every day."] },
      { ko: '일요일마다 우리는 하이킹을 가요.', en: "We go hiking every Sunday.", alt: ["We go hiking on Sundays."] },
      { ko: '저는 음악 듣는 것을 정말 좋아해요.', en: "I really love listening to music.", alt: ["I really like listening to music."] },
      { ko: '얼마나 자주 운동해요?', en: "How often do you exercise?", alt: ["How often do you work out?"] },
      { ko: '저는 게임을 거의 안 해요.', en: "I rarely play video games.", alt: ["I almost never play video games."] },
    ],
    words: [
      { ko: '취미', en: 'hobby' },
      { ko: '음악', en: 'music' },
      { ko: '영화', en: 'movie' },
      { ko: '책', en: 'book' },
      { ko: '운동', en: 'exercise' },
      { ko: '사진', en: 'photo' },
      { ko: '게임', en: 'game' },
      { ko: '수영', en: 'swimming' },
    ],
    distractorsEn: ['kitchen', 'yellow', 'doctor', 'winter', 'bread', 'street', 'shirt', 'cloudy'],
    distractorsKo: ['부엌', '노란색', '의사', '겨울', '빵', '거리', '셔츠', '흐림'],
  },
  {
    id: 's2u5',
    title: '직업',
    subtitle: '직업 묻고 답하기',
    icon: 'face',
    lessonCount: 5,
    pairs: [
      { ko: '무슨 일을 하세요?', en: "What do you do for work?", alt: ["What do you do for a living?"] },
      { ko: '저는 간호사예요.', en: "I am a nurse.", alt: ["I work as a nurse."] },
      { ko: '그는 병원에서 일해요.', en: "He works at a hospital.", alt: ["He works in a hospital."] },
      { ko: '저는 버스로 출근해요.', en: "I go to work by bus.", alt: ["I take the bus to work."] },
      { ko: '그녀는 학교에서 영어를 가르쳐요.', en: "She teaches English at a school.", alt: ["She teaches English at school."] },
      { ko: '사무실은 시내에 있어요.', en: "The office is downtown.", alt: ["Our office is downtown."] },
      { ko: '저는 아홉 시부터 여섯 시까지 일해요.', en: "I work from nine to six.", alt: ["I work nine to six."] },
      { ko: '당신의 직업이 마음에 들어요?', en: "Do you like your job?", alt: ["Do you enjoy your job?"] },
      { ko: '그는 회의 중이에요.', en: "He is in a meeting.", alt: ["He's in a meeting now."] },
      { ko: '저는 새 직장을 찾고 있어요.', en: "I am looking for a new job.", alt: ["I'm looking for a new job."] },
      { ko: '우리 상사는 정말 친절해요.', en: "My boss is very kind.", alt: ["My boss is really nice."] },
      { ko: '저는 집에서 일할 수 있어요.', en: "I can work from home.", alt: ["I am able to work from home."] },
    ],
    words: [
      { ko: '직업', en: 'job' },
      { ko: '의사', en: 'doctor' },
      { ko: '간호사', en: 'nurse' },
      { ko: '선생님', en: 'teacher' },
      { ko: '사무실', en: 'office' },
      { ko: '병원', en: 'hospital' },
      { ko: '회사', en: 'company' },
      { ko: '상사', en: 'boss' },
    ],
    distractorsEn: ['umbrella', 'apple', 'soccer', 'rainy', 'window', 'purple', 'lunch', 'river'],
    distractorsKo: ['우산', '사과', '축구', '노래', '창문', '보라색', '점심', '강물'],
  },
  {
    id: 's2u6',
    title: '길 찾기',
    subtitle: '길 묻고 안내하기',
    icon: 'plane',
    lessonCount: 5,
    pairs: [
      { ko: '실례합니다, 은행이 어디에 있나요?', en: "Excuse me, where is the bank?", alt: ["Excuse me, where's the bank?"] },
      { ko: '두 블록 직진하세요.', en: "Go straight for two blocks.", alt: ["Walk straight for two blocks."] },
      { ko: '다음 모퉁이에서 좌회전하세요.', en: "Turn left at the next corner.", alt: ["Take a left at the next corner."] },
      { ko: '지하철역은 병원 옆에 있어요.', en: "The subway station is next to the hospital.", alt: ["The subway station is beside the hospital."] },
      { ko: '여기서 멀어요?', en: "Is it far from here?", alt: ["Is that far from here?"] },
      { ko: '걸어서 십 분 걸려요.', en: "It takes ten minutes on foot.", alt: ["It takes ten minutes to walk."] },
      { ko: '공항에 가는 버스가 있나요?', en: "Is there a bus to the airport?", alt: ["Is there a bus that goes to the airport?"] },
      { ko: '신호등에서 우회전하세요.', en: "Turn right at the traffic light.", alt: ["Take a right at the traffic light."] },
      { ko: '길을 잃은 것 같아요.', en: "I think I am lost.", alt: ["I think I'm lost."] },
      { ko: '박물관은 공원 건너편에 있어요.', en: "The museum is across from the park.", alt: ["The museum is opposite the park."] },
      { ko: '지도를 보여 줄 수 있어요?', en: "Can you show me the map?", alt: ["Could you show me the map?"] },
      { ko: '저기서 택시를 탈 수 있어요.', en: "You can take a taxi over there.", alt: ["You can get a taxi over there."] },
    ],
    words: [
      { ko: '길', en: 'street' },
      { ko: '지도', en: 'map' },
      { ko: '왼쪽', en: 'left' },
      { ko: '오른쪽', en: 'right' },
      { ko: '버스', en: 'bus' },
      { ko: '지하철', en: 'subway' },
      { ko: '택시', en: 'taxi' },
      { ko: '공항', en: 'airport' },
    ],
    distractorsEn: ['kitchen', 'summer', 'nurse', 'apple', 'guitar', 'window', 'yellow', 'lunch'],
    distractorsKo: ['부엌', '여름', '간호사', '사과', '기타', '창문', '노란색', '점심'],
  },
];
